pipeline:
  build:
    image: golang:1.19
    commands:
      - go version

  vet:
    image: golang:1.19
    commands:
      - go vet ./...

  format:
    image: golang:1.19
    commands:
      - go fmt ./...

  test:
    image: golang:1.19
    commands:
      - go test -v ./...

  start-docker-compose:
    image: docker/compose:1.29.2
    commands:
      - docker-compose up -d
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_MAX_CONNECTIONS=${POSTGRES_MAX_CONNECTIONS}
      - POSTGRES_SHARED_BUFFERS=${POSTGRES_SHARED_BUFFERS}
      - POSTGRES_WORK_MEM=${POSTGRES_WORK_MEM}
      - POSTGRES_EFFECTIVE_CACHE_SIZE=${POSTGRES_EFFECTIVE_CACHE_SIZE}
      - PGADMIN_DEFAULT_USER=${PGADMIN_DEFAULT_USER}
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
