pipeline:
  build:
    image: golang:1.19
    commands:
      - go version

  vet:
    image: golang:1.19
    commands:
      - go vet ./...

  format:
    image: golang:1.19
    commands:
      - go fmt ./...

  test:
    image: golang:1.19
    commands:
      - go test -v ./...

  start-docker-compose:
    image: docker/compose
    environment:
      DOCKER_HOST: "unix:///var/run/docker.sock"
    commands:
      - source .env && docker-compose up -d
