pipeline:
  build:
    image: golang:1.19
    commands:
      - go version

  vet:
    image: golang:1.19
    commands:
      - go vet ./...

  format:
    image: golang:1.19
    commands:
      - go fmt ./...

  test:
    image: golang:1.19
    commands:
      - go test -v ./...

  build-docker-compose:
    image: docker/compose:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker-compose build
